// /// API DATA

// var myHeaders = new Headers();
// myHeaders.append("X-RapidAPI-Key", "8e983a8afemsh48d560cda2e9f8bp1cfb60jsn5380fb86e94b");
// myHeaders.append("X-RapidAPI-Host", "coronavirus-monitor.p.rapidapi.com");

// var requestOptions = {
//   method: 'GET',
//   headers: myHeaders,
//   redirect: 'follow'
// };

// var obj;

// fetch("https://coronavirus-monitor.p.rapidapi.com/coronavirus/cases_by_country.php", requestOptions)
// .then(response => response.json())
// .then(data => obj = data)
// .then(() => console.log("US Cases " + obj.countries_stat[1].cases));

/// HARD CODED DATA BEING USED CURRENTLY:
let covidCases = [
    {
        "country_name": "",
        "cases": "721",
        "deaths": "14",
        "region": "",
        "total_recovered": "639",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "7",
        "active_cases": "68",
        "total_cases_per_1m_population": "0"
    },
    {
        "country_name": "USA",
        "cases": "614,246",
        "deaths": "26,064",
        "region": "",
        "total_recovered": "38,820",
        "new_deaths": "17",
        "new_cases": "360",
        "serious_critical": "13,473",
        "active_cases": "549,362",
        "total_cases_per_1m_population": "1,856"
    },
    {
        "country_name": "Spain",
        "cases": "177,633",
        "deaths": "18,579",
        "region": "",
        "total_recovered": "70,853",
        "new_deaths": "324",
        "new_cases": "3,573",
        "serious_critical": "7,371",
        "active_cases": "88,201",
        "total_cases_per_1m_population": "3,799"
    },
    {
        "country_name": "Italy",
        "cases": "162,488",
        "deaths": "21,067",
        "region": "",
        "total_recovered": "37,130",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3,186",
        "active_cases": "104,291",
        "total_cases_per_1m_population": "2,687"
    },
    {
        "country_name": "France",
        "cases": "143,303",
        "deaths": "15,729",
        "region": "",
        "total_recovered": "28,805",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "6,730",
        "active_cases": "98,769",
        "total_cases_per_1m_population": "2,195"
    },
    {
        "country_name": "Germany",
        "cases": "132,210",
        "deaths": "3,495",
        "region": "",
        "total_recovered": "72,600",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "4,288",
        "active_cases": "56,115",
        "total_cases_per_1m_population": "1,578"
    },
    {
        "country_name": "UK",
        "cases": "93,873",
        "deaths": "12,107",
        "region": "",
        "total_recovered": "N/A",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1,559",
        "active_cases": "81,422",
        "total_cases_per_1m_population": "1,383"
    },
    {
        "country_name": "Iran",
        "cases": "76,389",
        "deaths": "4,777",
        "region": "",
        "total_recovered": "49,933",
        "new_deaths": "94",
        "new_cases": "1,512",
        "serious_critical": "3,643",
        "active_cases": "21,679",
        "total_cases_per_1m_population": "909"
    },
    {
        "country_name": "Turkey",
        "cases": "65,111",
        "deaths": "1,403",
        "region": "",
        "total_recovered": "4,799",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1,809",
        "active_cases": "58,909",
        "total_cases_per_1m_population": "772"
    },
    {
        "country_name": "Belgium",
        "cases": "33,573",
        "deaths": "4,440",
        "region": "",
        "total_recovered": "7,107",
        "new_deaths": "283",
        "new_cases": "2,454",
        "serious_critical": "1,204",
        "active_cases": "22,026",
        "total_cases_per_1m_population": "2,897"
    },
    {
        "country_name": "Netherlands",
        "cases": "28,153",
        "deaths": "3,134",
        "region": "",
        "total_recovered": "250",
        "new_deaths": "189",
        "new_cases": "734",
        "serious_critical": "1,358",
        "active_cases": "24,769",
        "total_cases_per_1m_population": "1,643"
    },
    {
        "country_name": "Canada",
        "cases": "27,063",
        "deaths": "903",
        "region": "",
        "total_recovered": "8,235",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "557",
        "active_cases": "17,925",
        "total_cases_per_1m_population": "717"
    },
    {
        "country_name": "Switzerland",
        "cases": "26,023",
        "deaths": "1,190",
        "region": "",
        "total_recovered": "14,700",
        "new_deaths": "16",
        "new_cases": "87",
        "serious_critical": "386",
        "active_cases": "10,133",
        "total_cases_per_1m_population": "3,007"
    },
    {
        "country_name": "Brazil",
        "cases": "25,758",
        "deaths": "1,557",
        "region": "",
        "total_recovered": "14,026",
        "new_deaths": "25",
        "new_cases": "496",
        "serious_critical": "296",
        "active_cases": "10,175",
        "total_cases_per_1m_population": "121"
    },
    {
        "country_name": "Russia",
        "cases": "24,490",
        "deaths": "198",
        "region": "",
        "total_recovered": "1,986",
        "new_deaths": "28",
        "new_cases": "3,388",
        "serious_critical": "8",
        "active_cases": "22,306",
        "total_cases_per_1m_population": "168"
    },
    {
        "country_name": "Portugal",
        "cases": "18,091",
        "deaths": "599",
        "region": "",
        "total_recovered": "383",
        "new_deaths": "32",
        "new_cases": "643",
        "serious_critical": "208",
        "active_cases": "17,109",
        "total_cases_per_1m_population": "1,774"
    },
    {
        "country_name": "Austria",
        "cases": "14,297",
        "deaths": "393",
        "region": "",
        "total_recovered": "8,098",
        "new_deaths": "9",
        "new_cases": "71",
        "serious_critical": "232",
        "active_cases": "5,806",
        "total_cases_per_1m_population": "1,587"
    },
    {
        "country_name": "Israel",
        "cases": "12,200",
        "deaths": "126",
        "region": "",
        "total_recovered": "2,309",
        "new_deaths": "3",
        "new_cases": "154",
        "serious_critical": "176",
        "active_cases": "9,765",
        "total_cases_per_1m_population": "1,410"
    },
    {
        "country_name": "Sweden",
        "cases": "11,927",
        "deaths": "1,203",
        "region": "",
        "total_recovered": "381",
        "new_deaths": "170",
        "new_cases": "482",
        "serious_critical": "954",
        "active_cases": "10,343",
        "total_cases_per_1m_population": "1,181"
    },
    {
        "country_name": "India",
        "cases": "11,555",
        "deaths": "396",
        "region": "",
        "total_recovered": "1,362",
        "new_deaths": "3",
        "new_cases": "68",
        "serious_critical": "0",
        "active_cases": "9,797",
        "total_cases_per_1m_population": "8"
    },
    {
        "country_name": "Ireland",
        "cases": "11,479",
        "deaths": "406",
        "region": "",
        "total_recovered": "77",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "194",
        "active_cases": "10,996",
        "total_cases_per_1m_population": "2,325"
    },
    {
        "country_name": "S. Korea",
        "cases": "10,591",
        "deaths": "225",
        "region": "",
        "total_recovered": "7,616",
        "new_deaths": "3",
        "new_cases": "27",
        "serious_critical": "55",
        "active_cases": "2,750",
        "total_cases_per_1m_population": "207"
    },
    {
        "country_name": "Peru",
        "cases": "10,303",
        "deaths": "230",
        "region": "",
        "total_recovered": "2,869",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "132",
        "active_cases": "7,204",
        "total_cases_per_1m_population": "312"
    },
    {
        "country_name": "Japan",
        "cases": "8,100",
        "deaths": "146",
        "region": "",
        "total_recovered": "853",
        "new_deaths": "0",
        "new_cases": "215",
        "serious_critical": "152",
        "active_cases": "7,101",
        "total_cases_per_1m_population": "64"
    },
    {
        "country_name": "Chile",
        "cases": "7,917",
        "deaths": "92",
        "region": "",
        "total_recovered": "2,646",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "387",
        "active_cases": "5,179",
        "total_cases_per_1m_population": "414"
    },
    {
        "country_name": "Ecuador",
        "cases": "7,603",
        "deaths": "369",
        "region": "",
        "total_recovered": "696",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "129",
        "active_cases": "6,538",
        "total_cases_per_1m_population": "431"
    },
    {
        "country_name": "Poland",
        "cases": "7,408",
        "deaths": "268",
        "region": "",
        "total_recovered": "668",
        "new_deaths": "5",
        "new_cases": "206",
        "serious_critical": "160",
        "active_cases": "6,472",
        "total_cases_per_1m_population": "196"
    },
    {
        "country_name": "Romania",
        "cases": "7,216",
        "deaths": "362",
        "region": "",
        "total_recovered": "1,217",
        "new_deaths": "11",
        "new_cases": "337",
        "serious_critical": "245",
        "active_cases": "5,637",
        "total_cases_per_1m_population": "375"
    },
    {
        "country_name": "Norway",
        "cases": "6,686",
        "deaths": "142",
        "region": "",
        "total_recovered": "32",
        "new_deaths": "3",
        "new_cases": "63",
        "serious_critical": "59",
        "active_cases": "6,512",
        "total_cases_per_1m_population": "1,233"
    },
    {
        "country_name": "Denmark",
        "cases": "6,681",
        "deaths": "309",
        "region": "",
        "total_recovered": "2,515",
        "new_deaths": "10",
        "new_cases": "170",
        "serious_critical": "100",
        "active_cases": "3,857",
        "total_cases_per_1m_population": "1,153"
    },
    {
        "country_name": "Australia",
        "cases": "6,447",
        "deaths": "63",
        "region": "",
        "total_recovered": "3,686",
        "new_deaths": "2",
        "new_cases": "47",
        "serious_critical": "76",
        "active_cases": "2,698",
        "total_cases_per_1m_population": "253"
    },
    {
        "country_name": "Czechia",
        "cases": "6,151",
        "deaths": "163",
        "region": "",
        "total_recovered": "676",
        "new_deaths": "2",
        "new_cases": "40",
        "serious_critical": "84",
        "active_cases": "5,312",
        "total_cases_per_1m_population": "574"
    },
    {
        "country_name": "Pakistan",
        "cases": "5,988",
        "deaths": "107",
        "region": "",
        "total_recovered": "1,446",
        "new_deaths": "11",
        "new_cases": "151",
        "serious_critical": "46",
        "active_cases": "4,435",
        "total_cases_per_1m_population": "27"
    },
    {
        "country_name": "Philippines",
        "cases": "5,453",
        "deaths": "349",
        "region": "",
        "total_recovered": "353",
        "new_deaths": "14",
        "new_cases": "230",
        "serious_critical": "1",
        "active_cases": "4,751",
        "total_cases_per_1m_population": "50"
    },
    {
        "country_name": "Mexico",
        "cases": "5,399",
        "deaths": "406",
        "region": "",
        "total_recovered": "2,125",
        "new_deaths": "74",
        "new_cases": "385",
        "serious_critical": "207",
        "active_cases": "2,868",
        "total_cases_per_1m_population": "42"
    },
    {
        "country_name": "Saudi Arabia",
        "cases": "5,369",
        "deaths": "73",
        "region": "",
        "total_recovered": "889",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "59",
        "active_cases": "4,407",
        "total_cases_per_1m_population": "154"
    },
    {
        "country_name": "Indonesia",
        "cases": "5,136",
        "deaths": "469",
        "region": "",
        "total_recovered": "446",
        "new_deaths": "10",
        "new_cases": "297",
        "serious_critical": "0",
        "active_cases": "4,221",
        "total_cases_per_1m_population": "19"
    },
    {
        "country_name": "Malaysia",
        "cases": "5,072",
        "deaths": "83",
        "region": "",
        "total_recovered": "2,647",
        "new_deaths": "1",
        "new_cases": "85",
        "serious_critical": "56",
        "active_cases": "2,342",
        "total_cases_per_1m_population": "157"
    },
    {
        "country_name": "UAE",
        "cases": "4,933",
        "deaths": "28",
        "region": "",
        "total_recovered": "933",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "3,972",
        "total_cases_per_1m_population": "499"
    },
    {
        "country_name": "Serbia",
        "cases": "4,465",
        "deaths": "94",
        "region": "",
        "total_recovered": "400",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "131",
        "active_cases": "3,971",
        "total_cases_per_1m_population": "511"
    },
    {
        "country_name": "Ukraine",
        "cases": "3,764",
        "deaths": "108",
        "region": "",
        "total_recovered": "143",
        "new_deaths": "10",
        "new_cases": "392",
        "serious_critical": "45",
        "active_cases": "3,513",
        "total_cases_per_1m_population": "86"
    },
    {
        "country_name": "Belarus",
        "cases": "3,728",
        "deaths": "36",
        "region": "",
        "total_recovered": "203",
        "new_deaths": "3",
        "new_cases": "447",
        "serious_critical": "68",
        "active_cases": "3,489",
        "total_cases_per_1m_population": "395"
    },
    {
        "country_name": "Qatar",
        "cases": "3,711",
        "deaths": "7",
        "region": "",
        "total_recovered": "406",
        "new_deaths": "0",
        "new_cases": "283",
        "serious_critical": "37",
        "active_cases": "3,298",
        "total_cases_per_1m_population": "1,288"
    },
    {
        "country_name": "Panama",
        "cases": "3,574",
        "deaths": "95",
        "region": "",
        "total_recovered": "72",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "106",
        "active_cases": "3,407",
        "total_cases_per_1m_population": "828"
    },
    {
        "country_name": "Luxembourg",
        "cases": "3,307",
        "deaths": "67",
        "region": "",
        "total_recovered": "500",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "30",
        "active_cases": "2,740",
        "total_cases_per_1m_population": "5,283"
    },
    {
        "country_name": "Dominican Republic",
        "cases": "3,286",
        "deaths": "183",
        "region": "",
        "total_recovered": "162",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "143",
        "active_cases": "2,941",
        "total_cases_per_1m_population": "303"
    },
    {
        "country_name": "Singapore",
        "cases": "3,252",
        "deaths": "10",
        "region": "",
        "total_recovered": "611",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "29",
        "active_cases": "2,631",
        "total_cases_per_1m_population": "556"
    },
    {
        "country_name": "Finland",
        "cases": "3,237",
        "deaths": "64",
        "region": "",
        "total_recovered": "300",
        "new_deaths": "0",
        "new_cases": "76",
        "serious_critical": "74",
        "active_cases": "2,873",
        "total_cases_per_1m_population": "584"
    },
    {
        "country_name": "Colombia",
        "cases": "2,979",
        "deaths": "127",
        "region": "",
        "total_recovered": "354",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "106",
        "active_cases": "2,498",
        "total_cases_per_1m_population": "59"
    },
    {
        "country_name": "Thailand",
        "cases": "2,643",
        "deaths": "43",
        "region": "",
        "total_recovered": "1,497",
        "new_deaths": "2",
        "new_cases": "30",
        "serious_critical": "61",
        "active_cases": "1,103",
        "total_cases_per_1m_population": "38"
    },
    {
        "country_name": "Argentina",
        "cases": "2,443",
        "deaths": "105",
        "region": "",
        "total_recovered": "559",
        "new_deaths": "3",
        "new_cases": "166",
        "serious_critical": "83",
        "active_cases": "1,779",
        "total_cases_per_1m_population": "54"
    },
    {
        "country_name": "South Africa",
        "cases": "2,415",
        "deaths": "27",
        "region": "",
        "total_recovered": "410",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "7",
        "active_cases": "1,978",
        "total_cases_per_1m_population": "41"
    },
    {
        "country_name": "Egypt",
        "cases": "2,350",
        "deaths": "178",
        "region": "",
        "total_recovered": "589",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "1,583",
        "total_cases_per_1m_population": "23"
    },
    {
        "country_name": "Greece",
        "cases": "2,170",
        "deaths": "101",
        "region": "",
        "total_recovered": "269",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "76",
        "active_cases": "1,800",
        "total_cases_per_1m_population": "208"
    },
    {
        "country_name": "Algeria",
        "cases": "2,070",
        "deaths": "326",
        "region": "",
        "total_recovered": "691",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "60",
        "active_cases": "1,053",
        "total_cases_per_1m_population": "47"
    },
    {
        "country_name": "Morocco",
        "cases": "1,988",
        "deaths": "127",
        "region": "",
        "total_recovered": "218",
        "new_deaths": "1",
        "new_cases": "100",
        "serious_critical": "1",
        "active_cases": "1,643",
        "total_cases_per_1m_population": "54"
    },
    {
        "country_name": "Moldova",
        "cases": "1,934",
        "deaths": "43",
        "region": "",
        "total_recovered": "171",
        "new_deaths": "2",
        "new_cases": "0",
        "serious_critical": "80",
        "active_cases": "1,720",
        "total_cases_per_1m_population": "479"
    },
    {
        "country_name": "Croatia",
        "cases": "1,741",
        "deaths": "34",
        "region": "",
        "total_recovered": "473",
        "new_deaths": "3",
        "new_cases": "37",
        "serious_critical": "31",
        "active_cases": "1,234",
        "total_cases_per_1m_population": "424"
    },
    {
        "country_name": "Iceland",
        "cases": "1,720",
        "deaths": "8",
        "region": "",
        "total_recovered": "989",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "8",
        "active_cases": "723",
        "total_cases_per_1m_population": "5,040"
    },
    {
        "country_name": "Hungary",
        "cases": "1,579",
        "deaths": "134",
        "region": "",
        "total_recovered": "192",
        "new_deaths": "12",
        "new_cases": "67",
        "serious_critical": "58",
        "active_cases": "1,253",
        "total_cases_per_1m_population": "163"
    },
    {
        "country_name": "Bahrain",
        "cases": "1,528",
        "deaths": "7",
        "region": "",
        "total_recovered": "648",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3",
        "active_cases": "873",
        "total_cases_per_1m_population": "898"
    },
    {
        "country_name": "Kuwait",
        "cases": "1,405",
        "deaths": "3",
        "region": "",
        "total_recovered": "206",
        "new_deaths": "0",
        "new_cases": "50",
        "serious_critical": "31",
        "active_cases": "1,196",
        "total_cases_per_1m_population": "329"
    },
    {
        "country_name": "Iraq",
        "cases": "1,400",
        "deaths": "78",
        "region": "",
        "total_recovered": "766",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "556",
        "total_cases_per_1m_population": "35"
    },
    {
        "country_name": "Estonia",
        "cases": "1,400",
        "deaths": "35",
        "region": "",
        "total_recovered": "117",
        "new_deaths": "4",
        "new_cases": "27",
        "serious_critical": "10",
        "active_cases": "1,248",
        "total_cases_per_1m_population": "1,055"
    },
    {
        "country_name": "New Zealand",
        "cases": "1,386",
        "deaths": "9",
        "region": "",
        "total_recovered": "728",
        "new_deaths": "0",
        "new_cases": "20",
        "serious_critical": "3",
        "active_cases": "649",
        "total_cases_per_1m_population": "287"
    },
    {
        "country_name": "Kazakhstan",
        "cases": "1,290",
        "deaths": "15",
        "region": "",
        "total_recovered": "220",
        "new_deaths": "1",
        "new_cases": "58",
        "serious_critical": "20",
        "active_cases": "1,055",
        "total_cases_per_1m_population": "69"
    },
    {
        "country_name": "Uzbekistan",
        "cases": "1,275",
        "deaths": "4",
        "region": "",
        "total_recovered": "99",
        "new_deaths": "0",
        "new_cases": "110",
        "serious_critical": "8",
        "active_cases": "1,172",
        "total_cases_per_1m_population": "38"
    },
    {
        "country_name": "Slovenia",
        "cases": "1,248",
        "deaths": "61",
        "region": "",
        "total_recovered": "165",
        "new_deaths": "5",
        "new_cases": "28",
        "serious_critical": "34",
        "active_cases": "1,022",
        "total_cases_per_1m_population": "600"
    },
    {
        "country_name": "Bangladesh",
        "cases": "1,231",
        "deaths": "50",
        "region": "",
        "total_recovered": "49",
        "new_deaths": "4",
        "new_cases": "219",
        "serious_critical": "1",
        "active_cases": "1,132",
        "total_cases_per_1m_population": "7"
    },
    {
        "country_name": "Azerbaijan",
        "cases": "1,197",
        "deaths": "13",
        "region": "",
        "total_recovered": "351",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "25",
        "active_cases": "833",
        "total_cases_per_1m_population": "118"
    },
    {
        "country_name": "Armenia",
        "cases": "1,111",
        "deaths": "17",
        "region": "",
        "total_recovered": "297",
        "new_deaths": "1",
        "new_cases": "44",
        "serious_critical": "30",
        "active_cases": "797",
        "total_cases_per_1m_population": "375"
    },
    {
        "country_name": "Bosnia and Herzegovina",
        "cases": "1,110",
        "deaths": "41",
        "region": "",
        "total_recovered": "253",
        "new_deaths": "1",
        "new_cases": "27",
        "serious_critical": "4",
        "active_cases": "816",
        "total_cases_per_1m_population": "338"
    },
    {
        "country_name": "Lithuania",
        "cases": "1,091",
        "deaths": "29",
        "region": "",
        "total_recovered": "138",
        "new_deaths": "0",
        "new_cases": "21",
        "serious_critical": "14",
        "active_cases": "924",
        "total_cases_per_1m_population": "401"
    },
    {
        "country_name": "Hong Kong",
        "cases": "1,017",
        "deaths": "4",
        "region": "",
        "total_recovered": "459",
        "new_deaths": "0",
        "new_cases": "4",
        "serious_critical": "10",
        "active_cases": "554",
        "total_cases_per_1m_population": "136"
    },
    {
        "country_name": "Oman",
        "cases": "910",
        "deaths": "4",
        "region": "",
        "total_recovered": "131",
        "new_deaths": "0",
        "new_cases": "97",
        "serious_critical": "3",
        "active_cases": "775",
        "total_cases_per_1m_population": "178"
    },
    {
        "country_name": "North Macedonia",
        "cases": "908",
        "deaths": "44",
        "region": "",
        "total_recovered": "86",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "15",
        "active_cases": "778",
        "total_cases_per_1m_population": "436"
    },
    {
        "country_name": "Slovakia",
        "cases": "863",
        "deaths": "2",
        "region": "",
        "total_recovered": "151",
        "new_deaths": "0",
        "new_cases": "28",
        "serious_critical": "5",
        "active_cases": "710",
        "total_cases_per_1m_population": "158"
    },
    {
        "country_name": "Cameroon",
        "cases": "848",
        "deaths": "14",
        "region": "",
        "total_recovered": "130",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "704",
        "total_cases_per_1m_population": "32"
    },
    {
        "country_name": "Afghanistan",
        "cases": "784",
        "deaths": "25",
        "region": "",
        "total_recovered": "43",
        "new_deaths": "2",
        "new_cases": "70",
        "serious_critical": "0",
        "active_cases": "716",
        "total_cases_per_1m_population": "20"
    },
    {
        "country_name": "Cuba",
        "cases": "766",
        "deaths": "21",
        "region": "",
        "total_recovered": "132",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "9",
        "active_cases": "613",
        "total_cases_per_1m_population": "68"
    },
    {
        "country_name": "Tunisia",
        "cases": "747",
        "deaths": "34",
        "region": "",
        "total_recovered": "43",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "89",
        "active_cases": "670",
        "total_cases_per_1m_population": "63"
    },
    {
        "country_name": "Bulgaria",
        "cases": "735",
        "deaths": "36",
        "region": "",
        "total_recovered": "105",
        "new_deaths": "1",
        "new_cases": "22",
        "serious_critical": "29",
        "active_cases": "594",
        "total_cases_per_1m_population": "106"
    },
    {
        "country_name": "Diamond Princess",
        "cases": "712",
        "deaths": "12",
        "region": "",
        "total_recovered": "639",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "7",
        "active_cases": "61",
        "total_cases_per_1m_population": "0"
    },
    {
        "country_name": "Cyprus",
        "cases": "695",
        "deaths": "12",
        "region": "",
        "total_recovered": "65",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "8",
        "active_cases": "618",
        "total_cases_per_1m_population": "576"
    },
    {
        "country_name": "Latvia",
        "cases": "666",
        "deaths": "5",
        "region": "",
        "total_recovered": "44",
        "new_deaths": "0",
        "new_cases": "9",
        "serious_critical": "3",
        "active_cases": "617",
        "total_cases_per_1m_population": "353"
    },
    {
        "country_name": "Andorra",
        "cases": "659",
        "deaths": "31",
        "region": "",
        "total_recovered": "128",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "17",
        "active_cases": "500",
        "total_cases_per_1m_population": "8,529"
    },
    {
        "country_name": "Lebanon",
        "cases": "658",
        "deaths": "21",
        "region": "",
        "total_recovered": "81",
        "new_deaths": "0",
        "new_cases": "17",
        "serious_critical": "33",
        "active_cases": "556",
        "total_cases_per_1m_population": "96"
    },
    {
        "country_name": "Ivory Coast",
        "cases": "638",
        "deaths": "6",
        "region": "",
        "total_recovered": "114",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "518",
        "total_cases_per_1m_population": "24"
    },
    {
        "country_name": "Ghana",
        "cases": "636",
        "deaths": "8",
        "region": "",
        "total_recovered": "17",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "2",
        "active_cases": "611",
        "total_cases_per_1m_population": "20"
    },
    {
        "country_name": "Costa Rica",
        "cases": "618",
        "deaths": "3",
        "region": "",
        "total_recovered": "66",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "14",
        "active_cases": "549",
        "total_cases_per_1m_population": "121"
    },
    {
        "country_name": "Niger",
        "cases": "570",
        "deaths": "14",
        "region": "",
        "total_recovered": "90",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "466",
        "total_cases_per_1m_population": "24"
    },
    {
        "country_name": "Burkina Faso",
        "cases": "528",
        "deaths": "30",
        "region": "",
        "total_recovered": "177",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "321",
        "total_cases_per_1m_population": "25"
    },
    {
        "country_name": "Albania",
        "cases": "494",
        "deaths": "25",
        "region": "",
        "total_recovered": "251",
        "new_deaths": "1",
        "new_cases": "19",
        "serious_critical": "5",
        "active_cases": "218",
        "total_cases_per_1m_population": "172"
    },
    {
        "country_name": "Uruguay",
        "cases": "492",
        "deaths": "8",
        "region": "",
        "total_recovered": "260",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "14",
        "active_cases": "224",
        "total_cases_per_1m_population": "142"
    },
    {
        "country_name": "Kyrgyzstan",
        "cases": "449",
        "deaths": "5",
        "region": "",
        "total_recovered": "78",
        "new_deaths": "0",
        "new_cases": "19",
        "serious_critical": "5",
        "active_cases": "366",
        "total_cases_per_1m_population": "69"
    },
    {
        "country_name": "Channel Islands",
        "cases": "440",
        "deaths": "13",
        "region": "",
        "total_recovered": "48",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "379",
        "total_cases_per_1m_population": "2,531"
    },
    {
        "country_name": "Honduras",
        "cases": "419",
        "deaths": "31",
        "region": "",
        "total_recovered": "9",
        "new_deaths": "5",
        "new_cases": "12",
        "serious_critical": "10",
        "active_cases": "379",
        "total_cases_per_1m_population": "42"
    },
    {
        "country_name": "Malta",
        "cases": "399",
        "deaths": "3",
        "region": "",
        "total_recovered": "44",
        "new_deaths": "0",
        "new_cases": "6",
        "serious_critical": "4",
        "active_cases": "352",
        "total_cases_per_1m_population": "904"
    },
    {
        "country_name": "Bolivia",
        "cases": "397",
        "deaths": "28",
        "region": "",
        "total_recovered": "7",
        "new_deaths": "0",
        "new_cases": "43",
        "serious_critical": "3",
        "active_cases": "362",
        "total_cases_per_1m_population": "34"
    },
    {
        "country_name": "Jordan",
        "cases": "397",
        "deaths": "7",
        "region": "",
        "total_recovered": "235",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "5",
        "active_cases": "155",
        "total_cases_per_1m_population": "39"
    },
    {
        "country_name": "Taiwan",
        "cases": "395",
        "deaths": "6",
        "region": "",
        "total_recovered": "137",
        "new_deaths": "0",
        "new_cases": "2",
        "serious_critical": "0",
        "active_cases": "252",
        "total_cases_per_1m_population": "17"
    },
    {
        "country_name": "Réunion",
        "cases": "391",
        "deaths": "0",
        "region": "",
        "total_recovered": "40",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3",
        "active_cases": "351",
        "total_cases_per_1m_population": "437"
    },
    {
        "country_name": "Nigeria",
        "cases": "373",
        "deaths": "11",
        "region": "",
        "total_recovered": "99",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "2",
        "active_cases": "263",
        "total_cases_per_1m_population": "2"
    },
    {
        "country_name": "San Marino",
        "cases": "372",
        "deaths": "36",
        "region": "",
        "total_recovered": "53",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "15",
        "active_cases": "283",
        "total_cases_per_1m_population": "10,963"
    },
    {
        "country_name": "Djibouti",
        "cases": "363",
        "deaths": "2",
        "region": "",
        "total_recovered": "53",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "308",
        "total_cases_per_1m_population": "367"
    },
    {
        "country_name": "Guinea",
        "cases": "363",
        "deaths": "0",
        "region": "",
        "total_recovered": "31",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "332",
        "total_cases_per_1m_population": "28"
    },
    {
        "country_name": "Mauritius",
        "cases": "324",
        "deaths": "9",
        "region": "",
        "total_recovered": "51",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3",
        "active_cases": "264",
        "total_cases_per_1m_population": "255"
    },
    {
        "country_name": "Senegal",
        "cases": "314",
        "deaths": "2",
        "region": "",
        "total_recovered": "190",
        "new_deaths": "0",
        "new_cases": "15",
        "serious_critical": "1",
        "active_cases": "122",
        "total_cases_per_1m_population": "19"
    },
    {
        "country_name": "Palestine",
        "cases": "308",
        "deaths": "2",
        "region": "",
        "total_recovered": "62",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "244",
        "total_cases_per_1m_population": "60"
    },
    {
        "country_name": "Georgia",
        "cases": "306",
        "deaths": "3",
        "region": "",
        "total_recovered": "69",
        "new_deaths": "0",
        "new_cases": "6",
        "serious_critical": "6",
        "active_cases": "234",
        "total_cases_per_1m_population": "77"
    },
    {
        "country_name": "Montenegro",
        "cases": "288",
        "deaths": "4",
        "region": "",
        "total_recovered": "46",
        "new_deaths": "0",
        "new_cases": "5",
        "serious_critical": "7",
        "active_cases": "238",
        "total_cases_per_1m_population": "459"
    },
    {
        "country_name": "Vietnam",
        "cases": "267",
        "deaths": "0",
        "region": "",
        "total_recovered": "171",
        "new_deaths": "0",
        "new_cases": "1",
        "serious_critical": "8",
        "active_cases": "96",
        "total_cases_per_1m_population": "3"
    },
    {
        "country_name": "Isle of Man",
        "cases": "256",
        "deaths": "4",
        "region": "",
        "total_recovered": "151",
        "new_deaths": "2",
        "new_cases": "2",
        "serious_critical": "13",
        "active_cases": "101",
        "total_cases_per_1m_population": "3,011"
    },
    {
        "country_name": "DRC",
        "cases": "241",
        "deaths": "20",
        "region": "",
        "total_recovered": "20",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "201",
        "total_cases_per_1m_population": "3"
    },
    {
        "country_name": "Sri Lanka",
        "cases": "235",
        "deaths": "7",
        "region": "",
        "total_recovered": "63",
        "new_deaths": "0",
        "new_cases": "2",
        "serious_critical": "1",
        "active_cases": "165",
        "total_cases_per_1m_population": "11"
    },
    {
        "country_name": "Kenya",
        "cases": "225",
        "deaths": "10",
        "region": "",
        "total_recovered": "53",
        "new_deaths": "1",
        "new_cases": "9",
        "serious_critical": "2",
        "active_cases": "162",
        "total_cases_per_1m_population": "4"
    },
    {
        "country_name": "Mayotte",
        "cases": "217",
        "deaths": "3",
        "region": "",
        "total_recovered": "69",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3",
        "active_cases": "145",
        "total_cases_per_1m_population": "795"
    },
    {
        "country_name": "Venezuela",
        "cases": "197",
        "deaths": "9",
        "region": "",
        "total_recovered": "111",
        "new_deaths": "0",
        "new_cases": "8",
        "serious_critical": "6",
        "active_cases": "77",
        "total_cases_per_1m_population": "7"
    },
    {
        "country_name": "Faeroe Islands",
        "cases": "184",
        "deaths": "0",
        "region": "",
        "total_recovered": "166",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "18",
        "total_cases_per_1m_population": "3,766"
    },
    {
        "country_name": "Guatemala",
        "cases": "180",
        "deaths": "5",
        "region": "",
        "total_recovered": "19",
        "new_deaths": "0",
        "new_cases": "13",
        "serious_critical": "3",
        "active_cases": "156",
        "total_cases_per_1m_population": "10"
    },
    {
        "country_name": "Paraguay",
        "cases": "161",
        "deaths": "8",
        "region": "",
        "total_recovered": "23",
        "new_deaths": "1",
        "new_cases": "2",
        "serious_critical": "1",
        "active_cases": "130",
        "total_cases_per_1m_population": "23"
    },
    {
        "country_name": "El Salvador",
        "cases": "159",
        "deaths": "6",
        "region": "",
        "total_recovered": "30",
        "new_deaths": "0",
        "new_cases": "10",
        "serious_critical": "2",
        "active_cases": "123",
        "total_cases_per_1m_population": "25"
    },
    {
        "country_name": "Martinique",
        "cases": "158",
        "deaths": "8",
        "region": "",
        "total_recovered": "73",
        "new_deaths": "2",
        "new_cases": "1",
        "serious_critical": "17",
        "active_cases": "77",
        "total_cases_per_1m_population": "421"
    },
    {
        "country_name": "Guadeloupe",
        "cases": "145",
        "deaths": "8",
        "region": "",
        "total_recovered": "67",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "13",
        "active_cases": "70",
        "total_cases_per_1m_population": "362"
    },
    {
        "country_name": "Mali",
        "cases": "144",
        "deaths": "13",
        "region": "",
        "total_recovered": "34",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "97",
        "total_cases_per_1m_population": "7"
    },
    {
        "country_name": "Brunei",
        "cases": "136",
        "deaths": "1",
        "region": "",
        "total_recovered": "108",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "2",
        "active_cases": "27",
        "total_cases_per_1m_population": "311"
    },
    {
        "country_name": "Rwanda",
        "cases": "134",
        "deaths": "0",
        "region": "",
        "total_recovered": "49",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "85",
        "total_cases_per_1m_population": "10"
    },
    {
        "country_name": "Gibraltar",
        "cases": "129",
        "deaths": "0",
        "region": "",
        "total_recovered": "104",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "25",
        "total_cases_per_1m_population": "3,829"
    },
    {
        "country_name": "Cambodia",
        "cases": "122",
        "deaths": "0",
        "region": "",
        "total_recovered": "96",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "26",
        "total_cases_per_1m_population": "7"
    },
    {
        "country_name": "Trinidad and Tobago",
        "cases": "113",
        "deaths": "8",
        "region": "",
        "total_recovered": "17",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "88",
        "total_cases_per_1m_population": "81"
    },
    {
        "country_name": "Madagascar",
        "cases": "108",
        "deaths": "0",
        "region": "",
        "total_recovered": "23",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "85",
        "total_cases_per_1m_population": "4"
    },
    {
        "country_name": "Jamaica",
        "cases": "105",
        "deaths": "5",
        "region": "",
        "total_recovered": "21",
        "new_deaths": "1",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "79",
        "total_cases_per_1m_population": "35"
    },
    {
        "country_name": "Monaco",
        "cases": "93",
        "deaths": "1",
        "region": "",
        "total_recovered": "6",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "5",
        "active_cases": "86",
        "total_cases_per_1m_population": "2,370"
    },
    {
        "country_name": "Aruba",
        "cases": "92",
        "deaths": "0",
        "region": "",
        "total_recovered": "32",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "60",
        "total_cases_per_1m_population": "862"
    },
    {
        "country_name": "French Guiana",
        "cases": "86",
        "deaths": "0",
        "region": "",
        "total_recovered": "51",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "35",
        "total_cases_per_1m_population": "288"
    },
    {
        "country_name": "Ethiopia",
        "cases": "85",
        "deaths": "3",
        "region": "",
        "total_recovered": "15",
        "new_deaths": "0",
        "new_cases": "3",
        "serious_critical": "0",
        "active_cases": "67",
        "total_cases_per_1m_population": "0.7"
    },
    {
        "country_name": "Togo",
        "cases": "81",
        "deaths": "3",
        "region": "",
        "total_recovered": "35",
        "new_deaths": "0",
        "new_cases": "4",
        "serious_critical": "0",
        "active_cases": "43",
        "total_cases_per_1m_population": "10"
    },
    {
        "country_name": "Gabon",
        "cases": "80",
        "deaths": "1",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "23",
        "serious_critical": "0",
        "active_cases": "75",
        "total_cases_per_1m_population": "36"
    },
    {
        "country_name": "Liechtenstein",
        "cases": "79",
        "deaths": "1",
        "region": "",
        "total_recovered": "55",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "23",
        "total_cases_per_1m_population": "2,072"
    },
    {
        "country_name": "Congo",
        "cases": "74",
        "deaths": "5",
        "region": "",
        "total_recovered": "10",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "59",
        "total_cases_per_1m_population": "13"
    },
    {
        "country_name": "Myanmar",
        "cases": "74",
        "deaths": "4",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "11",
        "serious_critical": "0",
        "active_cases": "68",
        "total_cases_per_1m_population": "1"
    },
    {
        "country_name": "Barbados",
        "cases": "73",
        "deaths": "5",
        "region": "",
        "total_recovered": "15",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "4",
        "active_cases": "53",
        "total_cases_per_1m_population": "254"
    },
    {
        "country_name": "Somalia",
        "cases": "60",
        "deaths": "2",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "2",
        "active_cases": "56",
        "total_cases_per_1m_population": "4"
    },
    {
        "country_name": "Liberia",
        "cases": "59",
        "deaths": "6",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "49",
        "total_cases_per_1m_population": "12"
    },
    {
        "country_name": "Tanzania",
        "cases": "59",
        "deaths": "3",
        "region": "",
        "total_recovered": "7",
        "new_deaths": "0",
        "new_cases": "6",
        "serious_critical": "0",
        "active_cases": "49",
        "total_cases_per_1m_population": "1.0"
    },
    {
        "country_name": "Bermuda",
        "cases": "57",
        "deaths": "5",
        "region": "",
        "total_recovered": "30",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3",
        "active_cases": "22",
        "total_cases_per_1m_population": "915"
    },
    {
        "country_name": "French Polynesia",
        "cases": "55",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "55",
        "total_cases_per_1m_population": "196"
    },
    {
        "country_name": "Uganda",
        "cases": "55",
        "deaths": "0",
        "region": "",
        "total_recovered": "8",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "47",
        "total_cases_per_1m_population": "1"
    },
    {
        "country_name": "Cayman Islands",
        "cases": "54",
        "deaths": "1",
        "region": "",
        "total_recovered": "6",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "3",
        "active_cases": "47",
        "total_cases_per_1m_population": "822"
    },
    {
        "country_name": "Sint Maarten",
        "cases": "52",
        "deaths": "9",
        "region": "",
        "total_recovered": "5",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "2",
        "active_cases": "38",
        "total_cases_per_1m_population": "1,213"
    },
    {
        "country_name": "Bahamas",
        "cases": "49",
        "deaths": "8",
        "region": "",
        "total_recovered": "6",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "35",
        "total_cases_per_1m_population": "125"
    },
    {
        "country_name": "Zambia",
        "cases": "48",
        "deaths": "2",
        "region": "",
        "total_recovered": "30",
        "new_deaths": "0",
        "new_cases": "3",
        "serious_critical": "1",
        "active_cases": "16",
        "total_cases_per_1m_population": "3"
    },
    {
        "country_name": "Guyana",
        "cases": "47",
        "deaths": "6",
        "region": "",
        "total_recovered": "8",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "5",
        "active_cases": "33",
        "total_cases_per_1m_population": "60"
    },
    {
        "country_name": "Macao",
        "cases": "45",
        "deaths": "0",
        "region": "",
        "total_recovered": "10",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "35",
        "total_cases_per_1m_population": "69"
    },
    {
        "country_name": "Guinea-Bissau",
        "cases": "43",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "43",
        "total_cases_per_1m_population": "22"
    },
    {
        "country_name": "Equatorial Guinea",
        "cases": "41",
        "deaths": "0",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "37",
        "total_cases_per_1m_population": "29"
    },
    {
        "country_name": "Haiti",
        "cases": "40",
        "deaths": "3",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "37",
        "total_cases_per_1m_population": "4"
    },
    {
        "country_name": "Benin",
        "cases": "35",
        "deaths": "1",
        "region": "",
        "total_recovered": "18",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "16",
        "total_cases_per_1m_population": "3"
    },
    {
        "country_name": "Libya",
        "cases": "35",
        "deaths": "1",
        "region": "",
        "total_recovered": "9",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "25",
        "total_cases_per_1m_population": "5"
    },
    {
        "country_name": "Eritrea",
        "cases": "35",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "35",
        "total_cases_per_1m_population": "10"
    },
    {
        "country_name": "Sudan",
        "cases": "32",
        "deaths": "5",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "23",
        "total_cases_per_1m_population": "0.7"
    },
    {
        "country_name": "Saint Martin",
        "cases": "32",
        "deaths": "2",
        "region": "",
        "total_recovered": "11",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "5",
        "active_cases": "19",
        "total_cases_per_1m_population": "828"
    },
    {
        "country_name": "Mongolia",
        "cases": "30",
        "deaths": "0",
        "region": "",
        "total_recovered": "5",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "25",
        "total_cases_per_1m_population": "9"
    },
    {
        "country_name": "Syria",
        "cases": "29",
        "deaths": "2",
        "region": "",
        "total_recovered": "5",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "22",
        "total_cases_per_1m_population": "2"
    },
    {
        "country_name": "Mozambique",
        "cases": "28",
        "deaths": "0",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "26",
        "total_cases_per_1m_population": "0.9"
    },
    {
        "country_name": "Antigua and Barbuda",
        "cases": "23",
        "deaths": "2",
        "region": "",
        "total_recovered": "3",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "18",
        "total_cases_per_1m_population": "235"
    },
    {
        "country_name": "Chad",
        "cases": "23",
        "deaths": "0",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "21",
        "total_cases_per_1m_population": "1"
    },
    {
        "country_name": "Maldives",
        "cases": "21",
        "deaths": "0",
        "region": "",
        "total_recovered": "16",
        "new_deaths": "0",
        "new_cases": "1",
        "serious_critical": "0",
        "active_cases": "5",
        "total_cases_per_1m_population": "39"
    },
    {
        "country_name": "Angola",
        "cases": "19",
        "deaths": "2",
        "region": "",
        "total_recovered": "5",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "12",
        "total_cases_per_1m_population": "0.6"
    },
    {
        "country_name": "Laos",
        "cases": "19",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "18",
        "total_cases_per_1m_population": "3"
    },
    {
        "country_name": "Zimbabwe",
        "cases": "18",
        "deaths": "3",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "1",
        "serious_critical": "0",
        "active_cases": "14",
        "total_cases_per_1m_population": "1"
    },
    {
        "country_name": "Belize",
        "cases": "18",
        "deaths": "2",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "16",
        "total_cases_per_1m_population": "45"
    },
    {
        "country_name": "New Caledonia",
        "cases": "18",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "17",
        "total_cases_per_1m_population": "63"
    },
    {
        "country_name": "Malawi",
        "cases": "16",
        "deaths": "2",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "14",
        "total_cases_per_1m_population": "0.8"
    },
    {
        "country_name": "Nepal",
        "cases": "16",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "15",
        "total_cases_per_1m_population": "0.5"
    },
    {
        "country_name": "Dominica",
        "cases": "16",
        "deaths": "0",
        "region": "",
        "total_recovered": "8",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "8",
        "total_cases_per_1m_population": "222"
    },
    {
        "country_name": "Fiji",
        "cases": "16",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "16",
        "total_cases_per_1m_population": "18"
    },
    {
        "country_name": "Namibia",
        "cases": "16",
        "deaths": "0",
        "region": "",
        "total_recovered": "3",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "13",
        "total_cases_per_1m_population": "6"
    },
    {
        "country_name": "Saint Lucia",
        "cases": "15",
        "deaths": "0",
        "region": "",
        "total_recovered": "11",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "4",
        "total_cases_per_1m_population": "82"
    },
    {
        "country_name": "Eswatini",
        "cases": "15",
        "deaths": "0",
        "region": "",
        "total_recovered": "8",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "7",
        "total_cases_per_1m_population": "13"
    },
    {
        "country_name": "Curaçao",
        "cases": "14",
        "deaths": "1",
        "region": "",
        "total_recovered": "10",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "3",
        "total_cases_per_1m_population": "85"
    },
    {
        "country_name": "Grenada",
        "cases": "14",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "2",
        "active_cases": "14",
        "total_cases_per_1m_population": "124"
    },
    {
        "country_name": "Saint Kitts and Nevis",
        "cases": "14",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "14",
        "total_cases_per_1m_population": "263"
    },
    {
        "country_name": "Botswana",
        "cases": "13",
        "deaths": "1",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "12",
        "total_cases_per_1m_population": "6"
    },
    {
        "country_name": "Sierra Leone",
        "cases": "13",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "2",
        "serious_critical": "0",
        "active_cases": "13",
        "total_cases_per_1m_population": "2"
    },
    {
        "country_name": "St. Vincent Grenadines",
        "cases": "12",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "11",
        "total_cases_per_1m_population": "108"
    },
    {
        "country_name": "Cabo Verde",
        "cases": "11",
        "deaths": "1",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "9",
        "total_cases_per_1m_population": "20"
    },
    {
        "country_name": "CAR",
        "cases": "11",
        "deaths": "0",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "7",
        "total_cases_per_1m_population": "2"
    },
    {
        "country_name": "Falkland Islands",
        "cases": "11",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "10",
        "total_cases_per_1m_population": "3,161"
    },
    {
        "country_name": "Greenland",
        "cases": "11",
        "deaths": "0",
        "region": "",
        "total_recovered": "11",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "0",
        "total_cases_per_1m_population": "194"
    },
    {
        "country_name": "Montserrat",
        "cases": "11",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "1",
        "active_cases": "10",
        "total_cases_per_1m_population": "2,204"
    },
    {
        "country_name": "Seychelles",
        "cases": "11",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "11",
        "total_cases_per_1m_population": "112"
    },
    {
        "country_name": "Suriname",
        "cases": "10",
        "deaths": "1",
        "region": "",
        "total_recovered": "6",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "3",
        "total_cases_per_1m_population": "17"
    },
    {
        "country_name": "Turks and Caicos",
        "cases": "10",
        "deaths": "1",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "9",
        "total_cases_per_1m_population": "258"
    },
    {
        "country_name": "MS Zaandam",
        "cases": "9",
        "deaths": "2",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "7",
        "total_cases_per_1m_population": "0"
    },
    {
        "country_name": "Gambia",
        "cases": "9",
        "deaths": "1",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "6",
        "total_cases_per_1m_population": "4"
    },
    {
        "country_name": "Nicaragua",
        "cases": "9",
        "deaths": "1",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "4",
        "total_cases_per_1m_population": "1"
    },
    {
        "country_name": "Vatican City",
        "cases": "8",
        "deaths": "0",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "6",
        "total_cases_per_1m_population": "9,988"
    },
    {
        "country_name": "Timor-Leste",
        "cases": "8",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "2",
        "serious_critical": "0",
        "active_cases": "7",
        "total_cases_per_1m_population": "6"
    },
    {
        "country_name": "Mauritania",
        "cases": "7",
        "deaths": "1",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "4",
        "total_cases_per_1m_population": "2"
    },
    {
        "country_name": "St. Barth",
        "cases": "6",
        "deaths": "0",
        "region": "",
        "total_recovered": "4",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "2",
        "total_cases_per_1m_population": "607"
    },
    {
        "country_name": "Western Sahara",
        "cases": "6",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "6",
        "total_cases_per_1m_population": "10"
    },
    {
        "country_name": "Burundi",
        "cases": "5",
        "deaths": "1",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "4",
        "total_cases_per_1m_population": "0.4"
    },
    {
        "country_name": "Bhutan",
        "cases": "5",
        "deaths": "0",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "3",
        "total_cases_per_1m_population": "6"
    },
    {
        "country_name": "Sao Tome and Principe",
        "cases": "4",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "4",
        "total_cases_per_1m_population": "18"
    },
    {
        "country_name": "South Sudan",
        "cases": "4",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "4",
        "total_cases_per_1m_population": "0.4"
    },
    {
        "country_name": "Anguilla",
        "cases": "3",
        "deaths": "0",
        "region": "",
        "total_recovered": "1",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "2",
        "total_cases_per_1m_population": "200"
    },
    {
        "country_name": "British Virgin Islands",
        "cases": "3",
        "deaths": "0",
        "region": "",
        "total_recovered": "2",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "1",
        "total_cases_per_1m_population": "99"
    },
    {
        "country_name": "Caribbean Netherlands",
        "cases": "3",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "3",
        "total_cases_per_1m_population": "114"
    },
    {
        "country_name": "Papua New Guinea",
        "cases": "2",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "2",
        "total_cases_per_1m_population": "0.2"
    },
    {
        "country_name": "Saint Pierre Miquelon",
        "cases": "1",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "1",
        "total_cases_per_1m_population": "173"
    },
    {
        "country_name": "Yemen",
        "cases": "1",
        "deaths": "0",
        "region": "",
        "total_recovered": "0",
        "new_deaths": "0",
        "new_cases": "0",
        "serious_critical": "0",
        "active_cases": "1",
        "total_cases_per_1m_population": "0.03"
    },
    {
        "country_name": "China",
        "cases": "82,295",
        "deaths": "3,342",
        "region": "",
        "total_recovered": "77,816",
        "new_deaths": "1",
        "new_cases": "46",
        "serious_critical": "113",
        "active_cases": "1,137",
        "total_cases_per_1m_population": "57"
    }
]